version: '3'

services:
  omnikdatalogger:
    build: .
    image: omnikdatalogger:latest
    volumes:
      - "${PWD}/config.yaml:/config.yaml"
    expose:
      - "10004"
    logging:
      driver: json-file
      
